package com.jf.stock.model;

// Generated 2014-10-20 17:26:03 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Dayline generated by hbm2java
 */
@Entity
@Table(name = "dayline", catalog = "stock")
public class Dayline implements java.io.Serializable {

	private DaylineId id;
	private Long cv;
	private Double open;
	private Double high;
	private Double low;
	private Double close;
	private Double lclose;
	private Double vol;
	private Double amout;

	public Dayline() {
	}

	public Dayline(DaylineId id) {
		this.id = id;
	}

	public Dayline(DaylineId id, Long cv, Double open, Double high, Double low,
			Double close, Double lclose, Double vol, Double amout) {
		this.id = id;
		this.cv = cv;
		this.open = open;
		this.high = high;
		this.low = low;
		this.close = close;
		this.lclose = lclose;
		this.vol = vol;
		this.amout = amout;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "obj", column = @Column(name = "obj", nullable = false, length = 32)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false)) })
	public DaylineId getId() {
		return this.id;
	}

	public void setId(DaylineId id) {
		this.id = id;
	}

	@Column(name = "CV")
	public Long getCv() {
		return this.cv;
	}

	public void setCv(Long cv) {
		this.cv = cv;
	}

	@Column(name = "open", precision = 22, scale = 0)
	public Double getOpen() {
		return this.open;
	}

	public void setOpen(Double open) {
		this.open = open;
	}

	@Column(name = "high", precision = 22, scale = 0)
	public Double getHigh() {
		return this.high;
	}

	public void setHigh(Double high) {
		this.high = high;
	}

	@Column(name = "low", precision = 22, scale = 0)
	public Double getLow() {
		return this.low;
	}

	public void setLow(Double low) {
		this.low = low;
	}

	@Column(name = "close", precision = 22, scale = 0)
	public Double getClose() {
		return this.close;
	}

	public void setClose(Double close) {
		this.close = close;
	}

	@Column(name = "lclose", precision = 22, scale = 0)
	public Double getLclose() {
		return this.lclose;
	}

	public void setLclose(Double lclose) {
		this.lclose = lclose;
	}

	@Column(name = "vol", precision = 22, scale = 0)
	public Double getVol() {
		return this.vol;
	}

	public void setVol(Double vol) {
		this.vol = vol;
	}

	@Column(name = "amout", precision = 22, scale = 0)
	public Double getAmout() {
		return this.amout;
	}

	public void setAmout(Double amout) {
		this.amout = amout;
	}

}
