package com.jf.stock.model;

// Generated 2014-10-20 17:26:03 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Jsj generated by hbm2java
 */
@Entity
@Table(name = "jsj", catalog = "stock")
public class Jsj implements java.io.Serializable {

	private JsjId id;
	private double xs;
	private double zkt;

	public Jsj() {
	}

	public Jsj(JsjId id, double xs, double zkt) {
		this.id = id;
		this.xs = xs;
		this.zkt = zkt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "obj", column = @Column(name = "obj", nullable = false, length = 32)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false)) })
	public JsjId getId() {
		return this.id;
	}

	public void setId(JsjId id) {
		this.id = id;
	}

	@Column(name = "xs", nullable = false, precision = 22, scale = 0)
	public double getXs() {
		return this.xs;
	}

	public void setXs(double xs) {
		this.xs = xs;
	}

	@Column(name = "zkt", nullable = false, precision = 22, scale = 0)
	public double getZkt() {
		return this.zkt;
	}

	public void setZkt(double zkt) {
		this.zkt = zkt;
	}

}
