package com.jf.stock.model;

// Generated 2014-10-20 17:26:03 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Klyh generated by hbm2java
 */
@Entity
@Table(name = "klyh", catalog = "stock")
public class Klyh implements java.io.Serializable {

	private KlyhId id;
	private double zf;
	private double lb;
	private double highfd;
	private double df;
	private double slxs;

	public Klyh() {
	}

	public Klyh(KlyhId id, double zf, double lb, double highfd, double df,
			double slxs) {
		this.id = id;
		this.zf = zf;
		this.lb = lb;
		this.highfd = highfd;
		this.df = df;
		this.slxs = slxs;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "obj", column = @Column(name = "obj", nullable = false, length = 32)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false)) })
	public KlyhId getId() {
		return this.id;
	}

	public void setId(KlyhId id) {
		this.id = id;
	}

	@Column(name = "zf", nullable = false, precision = 22, scale = 0)
	public double getZf() {
		return this.zf;
	}

	public void setZf(double zf) {
		this.zf = zf;
	}

	@Column(name = "lb", nullable = false, precision = 22, scale = 0)
	public double getLb() {
		return this.lb;
	}

	public void setLb(double lb) {
		this.lb = lb;
	}

	@Column(name = "highfd", nullable = false, precision = 22, scale = 0)
	public double getHighfd() {
		return this.highfd;
	}

	public void setHighfd(double highfd) {
		this.highfd = highfd;
	}

	@Column(name = "df", nullable = false, precision = 22, scale = 0)
	public double getDf() {
		return this.df;
	}

	public void setDf(double df) {
		this.df = df;
	}

	@Column(name = "slxs", nullable = false, precision = 22, scale = 0)
	public double getSlxs() {
		return this.slxs;
	}

	public void setSlxs(double slxs) {
		this.slxs = slxs;
	}

}
