package com.jf.stock.model;

// Generated 2014-10-20 17:26:03 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Macdjc generated by hbm2java
 */
@Entity
@Table(name = "macdjc", catalog = "stock")
public class Macdjc implements java.io.Serializable {

	private MacdjcId id;
	private double xs;
	private double dkt;
	private double zkt;
	private byte is10sc;
	private byte ismore0;

	public Macdjc() {
	}

	public Macdjc(MacdjcId id, double xs, double dkt, double zkt, byte is10sc,
			byte ismore0) {
		this.id = id;
		this.xs = xs;
		this.dkt = dkt;
		this.zkt = zkt;
		this.is10sc = is10sc;
		this.ismore0 = ismore0;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "obj", column = @Column(name = "obj", nullable = false, length = 32)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false)) })
	public MacdjcId getId() {
		return this.id;
	}

	public void setId(MacdjcId id) {
		this.id = id;
	}

	@Column(name = "xs", nullable = false, precision = 22, scale = 0)
	public double getXs() {
		return this.xs;
	}

	public void setXs(double xs) {
		this.xs = xs;
	}

	@Column(name = "dkt", nullable = false, precision = 22, scale = 0)
	public double getDkt() {
		return this.dkt;
	}

	public void setDkt(double dkt) {
		this.dkt = dkt;
	}

	@Column(name = "zkt", nullable = false, precision = 22, scale = 0)
	public double getZkt() {
		return this.zkt;
	}

	public void setZkt(double zkt) {
		this.zkt = zkt;
	}

	@Column(name = "is10sc", nullable = false)
	public byte getIs10sc() {
		return this.is10sc;
	}

	public void setIs10sc(byte is10sc) {
		this.is10sc = is10sc;
	}

	@Column(name = "ismore0", nullable = false)
	public byte getIsmore0() {
		return this.ismore0;
	}

	public void setIsmore0(byte ismore0) {
		this.ismore0 = ismore0;
	}

}
