package com.jf.stock.model;

// Generated 2014-10-20 17:26:03 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Plst generated by hbm2java
 */
@Entity
@Table(name = "plst", catalog = "stock")
public class Plst implements java.io.Serializable {

	private PlstId id;
	private double zf;
	private int day;
	private double lb;
	private double range;

	public Plst() {
	}

	public Plst(PlstId id, double zf, int day, double lb, double range) {
		this.id = id;
		this.zf = zf;
		this.day = day;
		this.lb = lb;
		this.range = range;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "obj", column = @Column(name = "obj", nullable = false, length = 32)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false)) })
	public PlstId getId() {
		return this.id;
	}

	public void setId(PlstId id) {
		this.id = id;
	}

	@Column(name = "zf", nullable = false, precision = 22, scale = 0)
	public double getZf() {
		return this.zf;
	}

	public void setZf(double zf) {
		this.zf = zf;
	}

	@Column(name = "day", nullable = false)
	public int getDay() {
		return this.day;
	}

	public void setDay(int day) {
		this.day = day;
	}

	@Column(name = "lb", nullable = false, precision = 22, scale = 0)
	public double getLb() {
		return this.lb;
	}

	public void setLb(double lb) {
		this.lb = lb;
	}

	@Column(name = "range_", nullable = false, precision = 22, scale = 0)
	public double getRange() {
		return this.range;
	}

	public void setRange(double range) {
		this.range = range;
	}

}
