package com.jf.stock.model;

// Generated 2014-10-20 17:26:03 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResultId generated by hbm2java
 */
@Embeddable
public class ResultId implements java.io.Serializable {

	private int date;
	private byte type;
	private String obj;

	public ResultId() {
	}

	public ResultId(int date, byte type, String obj) {
		this.date = date;
		this.type = type;
		this.obj = obj;
	}

	@Column(name = "date", nullable = false)
	public int getDate() {
		return this.date;
	}

	public void setDate(int date) {
		this.date = date;
	}

	@Column(name = "type", nullable = false)
	public byte getType() {
		return this.type;
	}

	public void setType(byte type) {
		this.type = type;
	}

	@Column(name = "obj", nullable = false, length = 20)
	public String getObj() {
		return this.obj;
	}

	public void setObj(String obj) {
		this.obj = obj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResultId))
			return false;
		ResultId castOther = (ResultId) other;

		return (this.getDate() == castOther.getDate())
				&& (this.getType() == castOther.getType())
				&& ((this.getObj() == castOther.getObj()) || (this.getObj() != null
						&& castOther.getObj() != null && this.getObj().equals(
						castOther.getObj())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDate();
		result = 37 * result + this.getType();
		result = 37 * result
				+ (getObj() == null ? 0 : this.getObj().hashCode());
		return result;
	}

}
