package com.jf.stock.model;

// Generated 2014-10-20 17:26:03 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * St22041MainId generated by hbm2java
 */
@Embeddable
public class St22041MainId implements java.io.Serializable {

	private String co;
	private String c2;

	public St22041MainId() {
	}

	public St22041MainId(String co, String c2) {
		this.co = co;
		this.c2 = c2;
	}

	@Column(name = "CO", nullable = false, length = 32)
	public String getCo() {
		return this.co;
	}

	public void setCo(String co) {
		this.co = co;
	}

	@Column(name = "C2", nullable = false, length = 165)
	public String getC2() {
		return this.c2;
	}

	public void setC2(String c2) {
		this.c2 = c2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof St22041MainId))
			return false;
		St22041MainId castOther = (St22041MainId) other;

		return ((this.getCo() == castOther.getCo()) || (this.getCo() != null
				&& castOther.getCo() != null && this.getCo().equals(
				castOther.getCo())))
				&& ((this.getC2() == castOther.getC2()) || (this.getC2() != null
						&& castOther.getC2() != null && this.getC2().equals(
						castOther.getC2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCo() == null ? 0 : this.getCo().hashCode());
		result = 37 * result + (getC2() == null ? 0 : this.getC2().hashCode());
		return result;
	}

}
