package com.jf.stock.model;

// Generated 2014-10-20 17:26:03 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * St32Id generated by hbm2java
 */
@Embeddable
public class St32Id implements java.io.Serializable {

	private String co;
	private String c4;

	public St32Id() {
	}

	public St32Id(String co) {
		this.co = co;
	}

	public St32Id(String co, String c4) {
		this.co = co;
		this.c4 = c4;
	}

	@Column(name = "CO", nullable = false, length = 32)
	public String getCo() {
		return this.co;
	}

	public void setCo(String co) {
		this.co = co;
	}

	@Column(name = "C4", length = 200)
	public String getC4() {
		return this.c4;
	}

	public void setC4(String c4) {
		this.c4 = c4;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof St32Id))
			return false;
		St32Id castOther = (St32Id) other;

		return ((this.getCo() == castOther.getCo()) || (this.getCo() != null
				&& castOther.getCo() != null && this.getCo().equals(
				castOther.getCo())))
				&& ((this.getC4() == castOther.getC4()) || (this.getC4() != null
						&& castOther.getC4() != null && this.getC4().equals(
						castOther.getC4())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCo() == null ? 0 : this.getCo().hashCode());
		result = 37 * result + (getC4() == null ? 0 : this.getC4().hashCode());
		return result;
	}

}
