package com.jf.stock.model;

// Generated 2014-10-20 17:26:03 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * St32 generated by hbm2java
 */
@Entity
@Table(name = "st32", catalog = "stock")
public class St32 implements java.io.Serializable {

	private St32Id id;

	public St32() {
	}

	public St32(St32Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "co", column = @Column(name = "CO", nullable = false, length = 32)),
			@AttributeOverride(name = "c4", column = @Column(name = "C4", length = 200)) })
	public St32Id getId() {
		return this.id;
	}

	public void setId(St32Id id) {
		this.id = id;
	}

}
