package com.jf.stock.model;

// Generated 2014-10-20 17:26:03 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tdz generated by hbm2java
 */
@Entity
@Table(name = "tdz", catalog = "stock")
public class Tdz implements java.io.Serializable {

	private TdzId id;
	private double length;
	private double dkt;
	private double zkt;
	private double lb;
	private byte issz;

	public Tdz() {
	}

	public Tdz(TdzId id, double length, double dkt, double zkt, double lb,
			byte issz) {
		this.id = id;
		this.length = length;
		this.dkt = dkt;
		this.zkt = zkt;
		this.lb = lb;
		this.issz = issz;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "obj", column = @Column(name = "obj", nullable = false, length = 32)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false)) })
	public TdzId getId() {
		return this.id;
	}

	public void setId(TdzId id) {
		this.id = id;
	}

	@Column(name = "length", nullable = false, precision = 22, scale = 0)
	public double getLength() {
		return this.length;
	}

	public void setLength(double length) {
		this.length = length;
	}

	@Column(name = "dkt", nullable = false, precision = 22, scale = 0)
	public double getDkt() {
		return this.dkt;
	}

	public void setDkt(double dkt) {
		this.dkt = dkt;
	}

	@Column(name = "zkt", nullable = false, precision = 22, scale = 0)
	public double getZkt() {
		return this.zkt;
	}

	public void setZkt(double zkt) {
		this.zkt = zkt;
	}

	@Column(name = "lb", nullable = false, precision = 22, scale = 0)
	public double getLb() {
		return this.lb;
	}

	public void setLb(double lb) {
		this.lb = lb;
	}

	@Column(name = "issz", nullable = false)
	public byte getIssz() {
		return this.issz;
	}

	public void setIssz(byte issz) {
		this.issz = issz;
	}

}
