package com.jf.stock.model;

// Generated 2014-10-20 17:26:03 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Yycdx generated by hbm2java
 */
@Entity
@Table(name = "yycdx", catalog = "stock")
public class Yycdx implements java.io.Serializable {

	private YycdxId id;
	private double zf;
	private int day;
	private String desc;
	private double dkt;
	private double zkt;
	private double lb;

	public Yycdx() {
	}

	public Yycdx(YycdxId id, double zf, int day, String desc, double dkt,
			double zkt, double lb) {
		this.id = id;
		this.zf = zf;
		this.day = day;
		this.desc = desc;
		this.dkt = dkt;
		this.zkt = zkt;
		this.lb = lb;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "obj", column = @Column(name = "obj", nullable = false, length = 32)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false)) })
	public YycdxId getId() {
		return this.id;
	}

	public void setId(YycdxId id) {
		this.id = id;
	}

	@Column(name = "zf", nullable = false, precision = 22, scale = 0)
	public double getZf() {
		return this.zf;
	}

	public void setZf(double zf) {
		this.zf = zf;
	}

	@Column(name = "day", nullable = false)
	public int getDay() {
		return this.day;
	}

	public void setDay(int day) {
		this.day = day;
	}

	@Column(name = "desc_", nullable = false, length = 32)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Column(name = "dkt", nullable = false, precision = 22, scale = 0)
	public double getDkt() {
		return this.dkt;
	}

	public void setDkt(double dkt) {
		this.dkt = dkt;
	}

	@Column(name = "zkt", nullable = false, precision = 22, scale = 0)
	public double getZkt() {
		return this.zkt;
	}

	public void setZkt(double zkt) {
		this.zkt = zkt;
	}

	@Column(name = "lb", nullable = false, precision = 22, scale = 0)
	public double getLb() {
		return this.lb;
	}

	public void setLb(double lb) {
		this.lb = lb;
	}

}
