package com.jf.stock.model;

// Generated 2014-10-20 17:26:03 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ztdk generated by hbm2java
 */
@Entity
@Table(name = "ztdk", catalog = "stock")
public class Ztdk implements java.io.Serializable {

	private ZtdkId id;
	private int date2;
	private int count;

	public Ztdk() {
	}

	public Ztdk(ZtdkId id, int date2, int count) {
		this.id = id;
		this.date2 = date2;
		this.count = count;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "obj", column = @Column(name = "obj", nullable = false, length = 32)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false)) })
	public ZtdkId getId() {
		return this.id;
	}

	public void setId(ZtdkId id) {
		this.id = id;
	}

	@Column(name = "date2", nullable = false)
	public int getDate2() {
		return this.date2;
	}

	public void setDate2(int date2) {
		this.date2 = date2;
	}

	@Column(name = "count", nullable = false)
	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

}
