package com.jf.stock.model;

// Generated 2014-10-20 17:26:03 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ztfx generated by hbm2java
 */
@Entity
@Table(name = "ztfx", catalog = "stock")
public class Ztfx implements java.io.Serializable {

	private ZtfxId id;
	private byte isyz;
	private double price;
	private double lb;
	private double maxpdate;
	private double minpdate;
	private double maxp;
	private double minp;
	private double maxvdate;
	private double minvdate;
	private double maxv;
	private double minv;
	private double minvprice;

	public Ztfx() {
	}

	public Ztfx(ZtfxId id, byte isyz, double price, double lb, double maxpdate,
			double minpdate, double maxp, double minp, double maxvdate,
			double minvdate, double maxv, double minv, double minvprice) {
		this.id = id;
		this.isyz = isyz;
		this.price = price;
		this.lb = lb;
		this.maxpdate = maxpdate;
		this.minpdate = minpdate;
		this.maxp = maxp;
		this.minp = minp;
		this.maxvdate = maxvdate;
		this.minvdate = minvdate;
		this.maxv = maxv;
		this.minv = minv;
		this.minvprice = minvprice;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "obj", column = @Column(name = "obj", nullable = false, length = 32)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false)) })
	public ZtfxId getId() {
		return this.id;
	}

	public void setId(ZtfxId id) {
		this.id = id;
	}

	@Column(name = "isyz", nullable = false)
	public byte getIsyz() {
		return this.isyz;
	}

	public void setIsyz(byte isyz) {
		this.isyz = isyz;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "lb", nullable = false, precision = 22, scale = 0)
	public double getLb() {
		return this.lb;
	}

	public void setLb(double lb) {
		this.lb = lb;
	}

	@Column(name = "maxpdate", nullable = false, precision = 22, scale = 0)
	public double getMaxpdate() {
		return this.maxpdate;
	}

	public void setMaxpdate(double maxpdate) {
		this.maxpdate = maxpdate;
	}

	@Column(name = "minpdate", nullable = false, precision = 22, scale = 0)
	public double getMinpdate() {
		return this.minpdate;
	}

	public void setMinpdate(double minpdate) {
		this.minpdate = minpdate;
	}

	@Column(name = "maxp", nullable = false, precision = 22, scale = 0)
	public double getMaxp() {
		return this.maxp;
	}

	public void setMaxp(double maxp) {
		this.maxp = maxp;
	}

	@Column(name = "minp", nullable = false, precision = 22, scale = 0)
	public double getMinp() {
		return this.minp;
	}

	public void setMinp(double minp) {
		this.minp = minp;
	}

	@Column(name = "maxvdate", nullable = false, precision = 22, scale = 0)
	public double getMaxvdate() {
		return this.maxvdate;
	}

	public void setMaxvdate(double maxvdate) {
		this.maxvdate = maxvdate;
	}

	@Column(name = "minvdate", nullable = false, precision = 22, scale = 0)
	public double getMinvdate() {
		return this.minvdate;
	}

	public void setMinvdate(double minvdate) {
		this.minvdate = minvdate;
	}

	@Column(name = "maxv", nullable = false, precision = 22, scale = 0)
	public double getMaxv() {
		return this.maxv;
	}

	public void setMaxv(double maxv) {
		this.maxv = maxv;
	}

	@Column(name = "minv", nullable = false, precision = 22, scale = 0)
	public double getMinv() {
		return this.minv;
	}

	public void setMinv(double minv) {
		this.minv = minv;
	}

	@Column(name = "minvprice", nullable = false, precision = 22, scale = 0)
	public double getMinvprice() {
		return this.minvprice;
	}

	public void setMinvprice(double minvprice) {
		this.minvprice = minvprice;
	}

}
